/**
 * List of all subjects taught at Katwanyaa Senior School
 */
export const ALL_SUBJECTS = [
  { value: 'English', label: 'English' },
  { value: 'English Language', label: 'English Language' },
  { value: 'Literature in English', label: 'Literature in English' },
  { value: 'Kiswahili', label: 'Kiswahili' },
  { value: 'Kiswahili Lugha', label: 'Kiswahili Lugha' },
  { value: 'Fasihi ya Kiswahili', label: 'Fasihi ya Kiswahili' },
  { value: 'Mathematics', label: 'Mathematics' },
  { value: 'General Mathematics', label: 'General Mathematics' },
  { value: 'Advanced Mathematics', label: 'Advanced Mathematics' },
  { value: 'Physics', label: 'Physics' },
  { value: 'Chemistry', label: 'Chemistry' },
  { value: 'Biology', label: 'Biology' },
  { value: 'General Science', label: 'General Science' },
  { value: 'Integrated Science', label: 'Integrated Science' },
  { value: 'History', label: 'History' },
  { value: 'History and Government', label: 'History and Government' },
  { value: 'Geography', label: 'Geography' },
  { value: 'Civics', label: 'Civics' },
  { value: 'Religious Education', label: 'Religious Education' },
  { value: 'Christian Religious Education', label: 'Christian Religious Education (CRE)' },
  { value: 'Islamic Religious Education', label: 'Islamic Religious Education (IRE)' },
  { value: 'Hindu Religious Education', label: 'Hindu Religious Education (HRE)' },
  { value: 'Computer Science', label: 'Computer Science' },
  { value: 'Computer Studies', label: 'Computer Studies' },
  { value: 'Information Technology', label: 'Information Technology' },
  { value: 'Business Studies', label: 'Business Studies' },
  { value: 'Accounting', label: 'Accounting' },
  { value: 'Commerce', label: 'Commerce' },
  { value: 'Economics', label: 'Economics' },
  { value: 'Agriculture', label: 'Agriculture' },
  { value: 'Agricultural Technology', label: 'Agricultural Technology' },
  { value: 'Physical Education', label: 'Physical Education' },
  { value: 'Sports and Recreation', label: 'Sports and Recreation' },
  { value: 'Art & Design', label: 'Art & Design' },
  { value: 'Fine Art', label: 'Fine Art' },
  { value: 'Drawing and Design', label: 'Drawing and Design' },
  { value: 'Music', label: 'Music' },
  { value: 'Dance', label: 'Dance' },
  { value: 'Drama and Theatre', label: 'Drama and Theatre' },
  { value: 'French', label: 'French' },
  { value: 'German', label: 'German' },
  { value: 'Arabic', label: 'Arabic' },
  { value: 'Chinese', label: 'Chinese' },
  { value: 'Kenya Sign Language', label: 'Kenya Sign Language' },
  { value: 'Indigenous Languages', label: 'Indigenous Languages' },
  { value: 'Home Science', label: 'Home Science' },
  { value: 'Foods and Nutrition', label: 'Foods and Nutrition' },
  { value: 'Clothing and Textiles', label: 'Clothing and Textiles' },
  { value: 'Aviation Technology', label: 'Aviation Technology' },
  { value: 'Building Construction', label: 'Building Construction' },
  { value: 'Electricity', label: 'Electricity' },
  { value: 'Metalwork', label: 'Metalwork' },
  { value: 'Power Mechanics', label: 'Power Mechanics' },
  { value: 'Woodwork', label: 'Woodwork' },
  { value: 'Media Technology', label: 'Media Technology' },
  { value: 'Marine and Fisheries Technology', label: 'Marine and Fisheries Technology' },
  { value: 'Community Service Learning', label: 'Community Service Learning' },
  { value: 'Life Skills', label: 'Life Skills' },
  { value: 'Language Activities', label: 'Language Activities' },
  { value: 'Literacy Activities', label: 'Literacy Activities' },
  { value: 'Kiswahili Language Activities', label: 'Kiswahili Language Activities' },
  { value: 'Mathematical Activities', label: 'Mathematical Activities' },
  { value: 'Environmental Activities', label: 'Environmental Activities' },
  { value: 'Psychomotor and Creative Activities', label: 'Psychomotor and Creative Activities' },
  { value: 'Movement and Creative Activities', label: 'Movement and Creative Activities' },
  { value: 'Hygiene and Nutrition Activities', label: 'Hygiene and Nutrition Activities' },
  { value: 'Indigenous Language Activities', label: 'Indigenous Language Activities' },
  { value: 'Science and Technology', label: 'Science and Technology' },
  { value: 'Social Studies', label: 'Social Studies' },
  { value: 'Creative Arts', label: 'Creative Arts' },
  { value: 'Creative Arts and Sports', label: 'Creative Arts and Sports' },
  { value: 'Agriculture and Nutrition', label: 'Agriculture and Nutrition' },
  { value: 'Pre-Technical Studies', label: 'Pre-Technical Studies' },
  { value: 'Health Education', label: 'Health Education' },
  { value: 'Visual Arts', label: 'Visual Arts' },
  { value: 'Performing Arts', label: 'Performing Arts' },
  { value: 'Sports Science', label: 'Sports Science' },
  { value: 'Core Mathematics', label: 'Core Mathematics' },
  { value: 'Essential Mathematics', label: 'Essential Mathematics' },
  { value: 'Pure Sciences', label: 'Pure Sciences' },
  { value: 'Applied Sciences', label: 'Applied Sciences' },
  { value: 'Technical Studies', label: 'Technical Studies' },
  { value: 'Career and Technology Studies', label: 'Career and Technology Studies' },
  { value: 'Arts and Sports Science', label: 'Arts and Sports Science' },
  { value: 'Social Sciences', label: 'Social Sciences' },
];

/**
 * Student classes/forms in the school
 */
export const STUDENT_CLASSES = [
  { value: 'Form 1', label: 'Form 1' },
  { value: 'Form 1A', label: 'Form 1A' },
  { value: 'Form 1B', label: 'Form 1B' },
  { value: 'Form 1C', label: 'Form 1C' },
  { value: 'Form 2', label: 'Form 2' },
  { value: 'Form 2A', label: 'Form 2A' },
  { value: 'Form 2B', label: 'Form 2B' },
  { value: 'Form 2C', label: 'Form 2C' },
  { value: 'Form 3', label: 'Form 3' },
  { value: 'Form 3A', label: 'Form 3A' },
  { value: 'Form 3B', label: 'Form 3B' },
  { value: 'Form 3C', label: 'Form 3C' },
  { value: 'Form 4', label: 'Form 4' },
  { value: 'Form 4A', label: 'Form 4A' },
  { value: 'Form 4B', label: 'Form 4B' },
  { value: 'Form 4C', label: 'Form 4C' },
];

/**
 * Grade levels mapping
 */
export const GRADE_LEVELS = [
  { value: '10', label: 'Grade 10 (Form 2)' },
  { value: '11', label: 'Grade 11 (Form 3)' },
  { value: '12', label: 'Grade 12 (Form 4)' },
];

export default {
  ALL_SUBJECTS,
  STUDENT_CLASSES,
  GRADE_LEVELS,
};